set_value:
  description: Write to a opcua node.
  fields:
    nodeid:
      description: the opcua nodeid to write to.
      example: "'ns=1;i=51010'"
    value:
      description: Value (single value) to write. Can be int, float, bool, string, byte
      example: "0"
    hub:
      description: Optional Modbus hub name. A hub with the name 'default' is used if not specified.
      example: "target1"